### ISSUE TITLE
Can a stable package version be published?

### ISSUE THREAD

**Issue by baronfel** [destructurama/fsharp#11]
@nblumhardt now that there's a prerelease out and it's been baking for a few months (https://www.nuget.org/packages/Destructurama.FSharp/1.1.0-dev-00023), would it be possible to push a stable version?  If not, are there things I can knock out to make that possible?

**Comment by nblumhardt** [comment]
Thanks for the nudge! Just opened #12 and will merge if the build's successful 👍

**Comment by baronfel** [comment]
Thank you for the quick turnaround!
