### ISSUE TITLE
Depreciate Destructurama.FSharp.NetCore?

### ISSUE THREAD

**Issue by TysonMN** [destructurama/fsharp#21]
I was confused by the difference between [`Destructurama.FSharp`](https://www.nuget.org/packages/Destructurama.FSharp) and [`Destructurama.FSharp.NetCore`](https://www.nuget.org/packages/Destructurama.FSharp.NetCore) on nuget.org until I saw that the latter hadn't been updated for several years.  I think it would be better if its documentation was similar to [`Serilog.Extras.FSharp`](https://www.nuget.org/packages/Serilog.Extras.FSharp), which says it is deprecated and that `Destructurama.FSharp` should be used instead.

**Comment by sungam3r** [comment]
@TysonMN to be able to do this one should be an package owner on nuget.org. ping @AntyaDev for help with this issue

**Comment by AntyaDev** [comment]
Hi @bartelink @sungam3r @TysonMN 
The package is unlisted now.

**Comment by sungam3r** [comment]
Thanks @AntyaDev .
