### ISSUE TITLE
How to declare from app.config?

### ISSUE THREAD

**Issue by Evangelink** [destructurama/fsharp#24]
Hi,

I could not find how to declare the `.Destructure.FSharpTypes()` part inside the `app.config` file. Any idea how to?

**Comment by baronfel** [comment]
That's a great question. I don't use the file-based configuration myself, so I'm not really equipped to answer that question.

**Comment by sungam3r** [comment]
@Evangelink please see https://github.com/serilog/serilog-settings-appsettings?tab=readme-ov-file#destructuring as a general purpose solution.
