### ISSUE TITLE
Add support for FSharp 5.0

### ISSUE THREAD

**Issue by AlexeyRaga** [destructurama/fsharp#25]
I am having this warning when using C# 5.0:

```
 warning NU1608: Detected package version outside of dependency constraint: Destructurama.FSharp 1.1.0 requires FSharp.Core (>= 4.6.2 && < 4.7.0) but version FSharp.Core 5.0.0 was resolved
```

But everything seems to be working fine.

Can the upper bound constraint be bumped?

**Comment by nblumhardt** [comment]
Sounds good to me 👍 - help welcome if anyone can take a look.

**Comment by AlexeyRaga** [comment]
I looked at it briefly, but I am a Haskell dev, not really and F# dev.. And I wasn't able to figure out where that upper bound is coming from, it isn't specified anywhere (that I can see) explicitly.

Perhaps someone who has better knowledge about it can take a look...
