### ISSUE TITLE
Built-in Result type not destructured

### ISSUE THREAD

**Issue by cmeeren** [destructurama/fsharp#8]
The FSharp.Core built-in `Result` type ([defined here](https://github.com/Microsoft/visualfsharp/blob/dbf7a9f07c3b4f424d6b063454f09a6872c04d71/src/fsharp/FSharp.Core/prim-types.fs#L3002-L3007)) is not destructured correctly:

```
Microsoft.FSharp.Core.FSharpResult`2[System.String,System.Object]
```

It seems it only runs `ToString` on it. I would expect this to be destructured the same way as other unions.

**Comment by nblumhardt** [comment]
Thanks, @cmeeren 👍 

If anyone has any ideas why this would be the case, a PR would be welcome.

**Comment by adamchester** [comment]
Thanks @cmeeren, it seems to be due to this union being a ‘Struct‘ and we did not add support for that kind of union yet. I agree we should add support for this in the same way as other unions.

Thanks again 👍

**Comment by cmeeren** [comment]
Happy to be of help, hope it's a quick fix. ^_^

**Comment by adamchester** [comment]
It should be a quick fix, we just need to find the APIs that we can use [instead of this](https://github.com/destructurama/fsharp/blob/202ff272e1c04bb5ad9c42a275595048f8c3b5bd/src/Destructurama.FSharp/DestructuramaFSharp.fs#L39)

```fsharp
            | t when FSharpType.IsUnion t ->
                let case, fields = FSharpValue.GetUnionFields(value, t)
                let properties = (case.GetFields(), fields) ||> Seq.map2 lep
                result <- StructureValue(properties, case.Name)
                true
```

**Comment by Zaid-Ajaj** [comment]
FYI, [Suave.SerilogExtensions](https://github.com/Zaid-Ajaj/Suave.SerilogExtensions) implements a proper destructuring mechanism for F# types (using `Json -> LogEvent`) see [Destructure.fs](https://github.com/Zaid-Ajaj/Suave.SerilogExtensions/blob/master/src/Suave.SerilogExtensions/Destructure.fs)

**Comment by adam-c-anderson** [comment]
Is this still really open? Just ran this in a test project:

```fsharp
Log.Logger <-
    LoggerConfiguration()
        .Destructure.FSharpTypes()
        .WriteTo.Console(Serilog.Formatting.Json.JsonFormatter())
        .CreateLogger()

type UnionData =
| Label of labelField:string
| Number of int

Log.Information("UnionData Label case {@label}", Label "Foo")
Log.Information("UnionData Number case {@number}", Number 42)
Log.Information("Result Ok case {@ok}", Ok "Bueno")
Log.Information("Result Error case {@error}", Error "Mal")
```

...and got this output

```
{"Timestamp":"2019-05-31T11:50:01.4639470-04:00","Level":"Information","MessageTemplate":"UnionData Label case {@label}","Properties":{"label":{"_typeTag":"Label","labelField":"Foo"}}}
{"Timestamp":"2019-05-31T11:50:01.4767652-04:00","Level":"Information","MessageTemplate":"UnionData Number case {@number}","Properties":{"number":{"_typeTag":"Number","Item":42}}}
{"Timestamp":"2019-05-31T11:50:01.4799127-04:00","Level":"Information","MessageTemplate":"Result Ok case {@ok}","Properties":{"ok":{"_typeTag":"Ok","ResultValue":"Bien"}}}
{"Timestamp":"2019-05-31T11:50:01.4807271-04:00","Level":"Information","MessageTemplate":"Result Error case {@error}","Properties":{"error":{"_typeTag":"Error","ErrorValue":"Mal"}}}
```

**Comment by baronfel** [comment]
This same structure of struct-handling will hit struct options (valuesome/valuenone) as well.

**Comment by baronfel** [comment]
I believe that all that needs to happen here is for #9 to be updated/finished and to upgrade to a more recent version of FSharp.Core (probably at least 4.6.2). Doing this will update the implementations of the FSharpType.Isxxxxx functions to return appropriate results for struct tuples, records, and unions. here's an example from the .net core FSI for 3.0 preview 7:

```
> let thing = ValueSome "ok";;
[<Struct>]
val thing : string voption = ValueSome "ok"

> let thingty = thing.GetType();;
val thingty : System.Type =
  Microsoft.FSharp.Core.FSharpValueOption`1[System.String]

> FSharp.Reflection.FSharpType.IsUnion thingty;;
val it : bool = true
```

**Comment by nblumhardt** [comment]
Thanks for the notes, @baronfel . This library's in need of some maintenance, if you or anyone following along are keen to jump in and modernize things the help would be appreciated. Cheers!

**Comment by baronfel** [comment]
I was planning on doing just that in a couple days/over the weekend. Are you a maintainer here (I'm not sure if the destructurama org is part of serilog proper)?

**Comment by nblumhardt** [comment]
I'm a maintainer though I'm not actively maintaining :-) ... I haven't touched F# in nearly 10 years, unfortunately
